apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kuard
  name: kuard
  namespace: kuard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kuard
  strategy: {}
  template:
    metadata:
      labels:
        app: kuard
    spec:
      containers:
      # gcr.io isn't a thing anymore, but there are lots of kuard images out there on dockerhub - PY
      # - image: gcr.io/kuar-demo/kuard-amd64:blue
      - image: wzxmtlw/kuard-demo:latest
        name: kuard-amd64
        resources: {}
